import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const BACKEND_ROOT = resolve(__dirname, '..', '..');
const MIGRATIONS_DIR = resolve(BACKEND_ROOT, 'drizzle');

/**
 * Migration SQL tests (RED → GREEN).
 *
 * The Drizzle migrator is essentially a SQL executor; the only thing that
 * matters is the generated SQL. This test reads the `drizzle/0000_*.sql`
 * file and asserts it contains the exact DDL the design + specs require.
 * If drizzle-kit ever changes the generated format in a way that affects
 * production semantics (FK action, unique-index syntax, etc.), this test
 * catches it before the migration reaches Postgres.
 *
 * The SQL is generated by `pnpm --filter backend db:generate` and is
 * committed alongside the source so this test runs from the repo state
 * alone (no Postgres, no Drizzle runtime).
 */

function readAllMigrations(): { name: string; sql: string }[] {
  if (!existsSync(MIGRATIONS_DIR)) {
    throw new Error(
      `Migrations folder not found: ${MIGRATIONS_DIR}. ` +
        'Run `pnpm --filter @shortpulse/backend db:generate` first.',
    );
  }
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort()
    .map((name) => ({
      name,
      sql: readFileSync(resolve(MIGRATIONS_DIR, name), 'utf8'),
    }));
}

let migrations: { name: string; sql: string }[];

beforeAll(() => {
  migrations = readAllMigrations();
});

describe('generated migrations — inventory', () => {
  it('produces at least one SQL file in packages/backend/drizzle/', () => {
    expect(
      migrations.length,
      'no migration files generated; run `pnpm db:generate`',
    ).toBeGreaterThan(0);
  });

  it('names the first migration `0000_*.sql` (the init migration)', () => {
    expect(migrations[0]?.name, 'first migration must be 0000_*.sql').toMatch(/^0000_.+\.sql$/);
  });
});

describe('generated migration SQL — links table', () => {
  let sql0000: string;
  beforeAll(() => {
    sql0000 = migrations[0]?.sql ?? '';
  });

  it('declares the `links` table', () => {
    // drizzle-kit emits `CREATE TABLE IF NOT EXISTS "links"`. We accept
    // any combination of "IF NOT EXISTS" and quoted/unquoted identifiers.
    expect(sql0000, 'must create the `links` table').toMatch(
      /CREATE TABLE\s+(?:IF NOT EXISTS\s+)?"?links"?/i,
    );
  });

  it('declares the columns id, original_url, slug, created_at, deleted_at on `links`', () => {
    for (const col of ['id', 'original_url', 'slug', 'created_at', 'deleted_at']) {
      expect(sql0000, `links must declare column \`${col}\``).toMatch(
        new RegExp(`"?${col}"?\\s+\\w+`, 'i'),
      );
    }
  });

  it('declares `links.id` as PRIMARY KEY with a uuid default', () => {
    expect(sql0000, 'links.id must be PRIMARY KEY').toMatch(
      /"id"\s+uuid\s+(?:NOT NULL\s+)?PRIMARY KEY/i,
    );
    expect(sql0000, 'links.id must have a uuid default').toMatch(
      /(gen_random_uuid|uuid_generate_v4)/i,
    );
  });

  it('declares `links.original_url`, `links.slug`, `links.created_at` as NOT NULL', () => {
    for (const col of ['original_url', 'slug', 'created_at']) {
      // Match the column, then any non-newline chars until the next
      // column-start or the close paren of the table. We can't use a
      // simple `[^,\n)]*` because default expressions contain `)`
      // (e.g. `now()`). We look for `NOT NULL` on the same statement
      // block, up to the next column declaration or the closing `);`.
      const re = new RegExp(`"?${col}"?[\\s\\S]*?NOT NULL`, 'i');
      // The match must be inside the same statement block (before the
      // next ");" or comma+newline+`"id"`). We assert by extracting a
      // small window per column.
      const lines = sql0000.split(/\r?\n/);
      const line = lines.find((l) => new RegExp(`"${col}"`, 'i').test(l));
      expect(line, `links.${col} line must exist`).toBeDefined();
      expect(line ?? '', `links.${col} must be NOT NULL`).toMatch(re);
    }
  });

  it('leaves `links.deleted_at` nullable (soft-delete flag, NULL = active)', () => {
    const re = /"deleted_at"\s+(?:timestamp(?:\s+with\s+time\s+zone)?|timestamptz)/i;
    expect(sql0000, 'links.deleted_at must be a timestamp column').toMatch(re);
    // The line that introduces deleted_at must NOT also include `NOT NULL`.
    const lines = sql0000.split(/\r?\n/);
    const delLine = lines.find((l) => /"deleted_at"/i.test(l));
    expect(delLine, 'links.deleted_at line must exist').toBeDefined();
    expect(delLine ?? '', 'links.deleted_at must NOT be NOT NULL').not.toMatch(/NOT NULL/i);
  });

  it('creates the unique index `links_slug_uidx` on `links(slug)`', () => {
    // drizzle-kit emits `CREATE UNIQUE INDEX IF NOT EXISTS "links_slug_uidx"
    // ON "links" USING btree ("slug")`.
    expect(sql0000, 'must create the unique slug index').toMatch(
      /CREATE\s+UNIQUE\s+INDEX\s+(?:IF NOT EXISTS\s+)?"?links_slug_uidx"?\s+ON\s+"?links"?[^()]*\(\s*"?slug"?\s*\)/i,
    );
  });

  it('creates the index `links_created_at_idx` on `links(created_at)`', () => {
    expect(sql0000, 'must create the created_at index').toMatch(
      /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF NOT EXISTS\s+)?"?links_created_at_idx"?\s+ON\s+"?links"?[^()]*\(\s*"?created_at"?\s*\)/i,
    );
  });
});

describe('generated migration SQL — analytics table', () => {
  let sql0000: string;
  beforeAll(() => {
    sql0000 = migrations[0]?.sql ?? '';
  });

  it('declares the `analytics` table', () => {
    expect(sql0000, 'must create the `analytics` table').toMatch(
      /CREATE TABLE\s+(?:IF NOT EXISTS\s+)?"?analytics"?/i,
    );
  });

  it('declares every analytics column: link_id, timestamp, ip, user_agent, referer, country, city, browser', () => {
    for (const col of [
      'link_id',
      'timestamp',
      'ip',
      'user_agent',
      'referer',
      'country',
      'city',
      'browser',
    ]) {
      expect(sql0000, `analytics must declare column \`${col}\``).toMatch(
        new RegExp(`"?${col}"?\\s+\\w+`, 'i'),
      );
    }
  });

  it('marks `analytics.link_id`, `analytics.timestamp`, `analytics.ip` NOT NULL', () => {
    for (const col of ['link_id', 'timestamp', 'ip']) {
      const lines = sql0000.split(/\r?\n/);
      const line = lines.find((l) => new RegExp(`"${col}"`, 'i').test(l));
      expect(line, `analytics.${col} line must exist`).toBeDefined();
      expect(line ?? '', `analytics.${col} must be NOT NULL`).toMatch(/NOT NULL/i);
    }
  });

  it('leaves `analytics.user_agent`, `analytics.referer`, `analytics.country`, `analytics.city`, `analytics.browser` nullable', () => {
    for (const col of ['user_agent', 'referer', 'country', 'city', 'browser']) {
      const lines = sql0000.split(/\r?\n/);
      const line = lines.find((l) => new RegExp(`"${col}"`, 'i').test(l));
      expect(line, `analytics.${col} line must exist`).toBeDefined();
      expect(line ?? '', `analytics.${col} must NOT be NOT NULL`).not.toMatch(/NOT NULL/i);
    }
  });

  it('declares the FK on `analytics.link_id` referencing `links.id` with `ON DELETE RESTRICT`', () => {
    // drizzle-kit wraps the FK in a DO block (idempotent) and uses
    // `"public"."links"("id")` as the reference target. We accept both
    // qualified and unqualified references.
    expect(sql0000, 'analytics must have a FK to links.id').toMatch(
      /FOREIGN KEY\s+\("?link_id"?\)\s+REFERENCES\s+(?:"?public"?\.)?"?links"?\s*\(\s*"?id"?\s*\)/i,
    );
    expect(sql0000, 'analytics FK must use ON DELETE RESTRICT (soft-delete + retention)').toMatch(
      /ON DELETE restrict/i,
    );
    // Explicit negative: it must NOT cascade (would orphan analytics rows).
    expect(sql0000, 'analytics FK must NOT cascade on delete').not.toMatch(/ON DELETE CASCADE/i);
  });

  it('creates the index `analytics_link_id_idx` on `analytics(link_id)`', () => {
    expect(sql0000, 'must create the link_id index').toMatch(
      /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF NOT EXISTS\s+)?"?analytics_link_id_idx"?\s+ON\s+"?analytics"?[^()]*\(\s*"?link_id"?\s*\)/i,
    );
  });

  it('creates the index `analytics_timestamp_desc_idx` on `analytics(timestamp)`', () => {
    expect(sql0000, 'must create the timestamp index').toMatch(
      /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF NOT EXISTS\s+)?"?analytics_timestamp_desc_idx"?\s+ON\s+"?analytics"?[^()]*\(\s*"?timestamp"?\s*\)/i,
    );
  });
});

describe('generated migration SQL — idempotency', () => {
  it('uses `IF NOT EXISTS` (or `IF NOT EXISTS` on indexes) so re-running is a no-op', () => {
    const sql0000 = migrations[0]?.sql ?? '';
    // drizzle-kit wraps every statement in `IF NOT EXISTS` to keep the
    // migration idempotent at the SQL level. We assert the marker
    // appears at least once (typically for the table and the indexes).
    const occurrences = (sql0000.match(/IF NOT EXISTS/gi) ?? []).length;
    expect(
      occurrences,
      'migration must contain `IF NOT EXISTS` markers for idempotency',
    ).toBeGreaterThan(0);
  });
});
