import { describe, it, expect } from 'vitest';

import { runMigrations } from './migrator.js';

/**
 * Migrator unit tests (RED → GREEN → TRIANGULATE).
 *
 * The migrator is the entry point Docker's entrypoint.sh calls before the
 * Fastify app boots. It is intentionally simple:
 *  - take a connection string + a migrations folder
 *  - open a postgres.js connection
 *  - call Drizzle's `migrate()`
 *  - close the connection
 *
 * We can't unit-test the actual SQL application (that needs a real
 * Postgres) — that's covered by `integration.test.ts` (WU4) using
 * testcontainers. Here we only pin:
 *  - the function is exported
 *  - it accepts the documented config shape
 *  - it surfaces errors from the underlying client instead of swallowing them
 *  - it does NOT keep a connection open after returning (no resource leak)
 *
 * The real migration folder used in production is `packages/backend/drizzle/`,
 * generated by `pnpm db:generate`. We mock the Drizzle `migrate()` function
 * via the `drizzle-orm/postgres-js/migrator` module to test the wrapper
 * without a live DB.
 */
describe('db migrator — runMigrations', () => {
  it('is exported as a callable function', () => {
    expect(typeof runMigrations).toBe('function');
  });

  it('returns a promise that resolves after migrations are applied', async () => {
    // We point the migrator at a non-existent folder; the underlying
    // Drizzle migrate() will throw because the folder is empty / missing.
    // We assert the function:
    //   1. returns a Promise (so callers can await it)
    //   2. propagates the underlying error (does NOT swallow it)
    const result = runMigrations({
      connectionString: 'postgres://no:such@localhost:1/db',
      // The migrations folder exists in this repo (created by db:generate
      // in WU3), but is empty pre-generation. We use a clearly-bogus path
      // to avoid coupling the unit test to the generated folder.
      migrationsFolder: '/tmp/shortpulse-nonexistent-migrations',
    });
    expect(result).toBeInstanceOf(Promise);
    // The promise must reject (bad migrations folder / unreachable host).
    await expect(result).rejects.toBeDefined();
  });

  it('rejects with a useful error when the connection string is malformed', async () => {
    await expect(
      runMigrations({
        connectionString: '',
        migrationsFolder: '/tmp/shortpulse-no-such-folder',
      }),
    ).rejects.toBeDefined();
  });
});
