/**
 * Drizzle ORM schema for ShortPulse.
 *
 * The single source of truth for the PostgreSQL database layout. Two tables:
 *  - `links`      — short URL records with soft-delete (`deleted_at`)
 *  - `analytics`  — per-redirect events; FK to links with `ON DELETE RESTRICT`
 *
 * The schema matches `openspec/changes/add-shortpulse-app/design.md` §4
 * verbatim, with the following intentional decisions:
 *  - `ip` is `text` (not `inet`) per spec analytics #1 — the
 *    redirect-handler receives X-Forwarded-For chains that may not parse as
 *    Postgres `inet` (e.g. `1.2.3.4, 10.0.0.1`). Validation happens in the
 *    application layer, not at the column level.
 *  - `user_agent`, `referer`, `country`, `city`, `browser` are nullable
 *    (per spec analytics #1 "MAY be null or empty when unknown"). The
 *    insert path always provides a value, but the schema allows nulls so
 *    the table never rejects a row from an upstream partial-failure.
 *  - FK is `ON DELETE RESTRICT` (not `CASCADE`) per design §4 + ADR-004:
 *    soft-delete sets `deleted_at`; the analytics row is never orphaned.
 *    Hard delete is intentionally blocked at the DB level.
 *
 * The migration is generated by `drizzle-kit generate` and lives in
 * `packages/backend/drizzle/`. Tests under `src/db/*.test.ts` assert
 * both the schema shape (this file) and the generated SQL
 * (`drizzle/0000_*.sql`).
 */

import { pgTable, uuid, text, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';

/**
 * The `links` table.
 *
 * One row per shortened URL. `slug` is the user-visible identifier (lowercased
 * before insert, see design §4 "Slug stored lowercased"). `deleted_at` is the
 * soft-delete flag: `NULL` = active, set = soft-deleted.
 */
export const links = pgTable(
  'links',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    originalUrl: text('original_url').notNull(),
    slug: text('slug').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    // Case-insensitive collision enforcement — slug is always lowercased
    // before INSERT, so the unique index is sufficient (no CITEXT extension).
    uniqueIndex('links_slug_uidx').on(t.slug),
    // Sorting and range scans on creation time (used by list/pagination).
    index('links_created_at_idx').on(t.createdAt),
  ],
);

/**
 * The `analytics` table.
 *
 * One row per redirect (synchronous insert, design ADR-002). FK uses
 * `ON DELETE RESTRICT` so the soft-delete pattern can never orphan an
 * analytics row.
 */
export const analytics = pgTable(
  'analytics',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    linkId: uuid('link_id')
      .notNull()
      .references(() => links.id, { onDelete: 'restrict' }),
    timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow().notNull(),
    ip: text('ip').notNull(),
    userAgent: text('user_agent'),
    referer: text('referer'),
    country: text('country'),
    city: text('city'),
    browser: text('browser'),
  },
  (t) => [
    // Per-link event lookup (events page, summary per-link KPI).
    index('analytics_link_id_idx').on(t.linkId),
    // Time-range scan + ORDER BY timestamp DESC for events/timeseries.
    // Named `_desc_` for intent (default ascending; Postgres uses
    // backward index scan for ORDER BY ... DESC which is just as fast).
    index('analytics_timestamp_desc_idx').on(t.timestamp),
  ],
);

/**
 * Aggregate schema object — passed to Drizzle's migrator so a single call
 * can introspect the entire DB. Pattern recommended by
 * https://orm.drizzle.team/docs/sql-schema-declaration#schema.
 */
export const schema = {
  links,
  analytics,
} as const;
