import { defineConfig } from 'vitest/config';

/**
 * Root vitest config. Tests live under `tests/` and in each package.
 * Coverage applies only to package `src/` directories to avoid penalising
 * config-sanity tests during the scaffold phase.
 *
 * The default environment is `node` (matches the backend, shared, and
 * root `tests/` config-sanity tests). Frontend `.tsx` tests use
 * jsdom — we route them via `environmentMatchGlobs` so the React +
 * DOM-dependent tests in `packages/frontend/src/**` get a real DOM.
 * The frontend's own `vite.config.ts` (used by
 * `pnpm --filter @shortpulse/frontend test`) defaults to jsdom too.
 *
 * Coverage (spec §10 + design §10): `@vitest/coverage-v8` with a
 * 90% line / branch / function / statement threshold per
 * `openspec/changes/add-shortpulse-app/design.md` §10 and the
 * links/analytics/health specs. Run with `pnpm test:coverage`.
 */
export default defineConfig({
  test: {
    include: [
      'tests/**/*.test.ts',
      'docker/**/*.test.ts',
      'packages/*/tests/**/*.test.ts',
      'packages/*/src/**/*.test.{ts,tsx}',
    ],
    setupFiles: ['./tests/setup.ts'],
    environment: 'node',
    environmentMatchGlobs: [['packages/frontend/src/**/*.test.tsx', 'jsdom']],
    globals: false,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json-summary'],
      include: ['packages/*/src/**'],
      exclude: [
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/index.ts',
        '**/types.ts',
        '**/*.d.ts',
        '**/main.tsx',
        // 1-line re-exports that exist purely to keep the router's
        // import path stable (e.g. `routes/index.tsx` re-exports
        // `LinksPage`). The actual code is covered at the source.
        '**/routes/index.tsx',
        '**/routes/analytics.tsx',
        // The TanStack Router file `routes.ts` (auto-generated by
        // the file-based router) is generated code, not hand-written.
        '**/routes.ts',
        // The frontend's test-setup file is plumbing, not behavior.
        '**/test-setup.ts',
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
  resolve: {
    alias: {
      '@shortpulse/shared': new URL('./packages/shared/src/index.ts', import.meta.url).pathname,
    },
  },
});
